# Generated by Django 3.0.3 on 2020-07-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=120)),
                ('owner', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('grade_level', models.CharField(choices=[('DC', 'Day Care'), ('KG', 'Kindergarten'), ('PRY', 'Primary'), ('JSS', 'Junior Secondary'), ('SSS', 'Senior Secondary')], default='DC', max_length=3)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simple_app.School')),
            ],
        ),
    ]
